### ISSUE TITLE
Build `ObliviousDoHConfigs`

### ISSUE THREAD

**Issue by tanyav2** [chris-wood/odoh#22]
An API that builds `ObliviousDoHConfigs` given a set of key pairs seems useful to have for generating client consumable configuration.

It could potentially look something like: 
```
func BuildOdohConfigsFromKeyPairs([]ObliviousDoHKeyPair) ObliviousDoHConfigs
```

**Comment by chris-wood** [comment]
#23 added an API to construct `ObliviousDoHConfigs` from a list of `ObliviousDoHConfig` structs, which an application can get from a list of `ObliviousDoHKeyPair` structs if needed. Closing this as a result.
